// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0ynf7o5sFdNEyfqO-2DBBgoSrSmZxmw',
    appId: '1:346356172725:web:deb6077445da109ac07bfc',
    messagingSenderId: '346356172725',
    projectId: 'empoderainformacoes',
    authDomain: 'empoderainformacoes.firebaseapp.com',
    storageBucket: 'empoderainformacoes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN4j8cncN2EANubUnok7K_hRa-oysdmW0',
    appId: '1:346356172725:android:6ac8a385020ad436c07bfc',
    messagingSenderId: '346356172725',
    projectId: 'empoderainformacoes',
    storageBucket: 'empoderainformacoes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Ef6YwIZlNJIpTyKGrQ4-LHbxzGw-gfY',
    appId: '1:346356172725:ios:1bf2faad07b637dfc07bfc',
    messagingSenderId: '346356172725',
    projectId: 'empoderainformacoes',
    storageBucket: 'empoderainformacoes.appspot.com',
    iosBundleId: 'com.example.empoderainformacoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Ef6YwIZlNJIpTyKGrQ4-LHbxzGw-gfY',
    appId: '1:346356172725:ios:ce9ba8830247ef5ac07bfc',
    messagingSenderId: '346356172725',
    projectId: 'empoderainformacoes',
    storageBucket: 'empoderainformacoes.appspot.com',
    iosBundleId: 'com.example.empoderainformacoes.RunnerTests',
  );
}
